/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/version': {
        get: operations['getVersion'];
    };
    '/auth/kakao': {
        post: operations['postAuthKakao'];
    };
    '/me': {
        get: operations['getMe'];
    };
    '/recommendation_nickname': {
        get: operations['getRecommendation_nickname'];
    };
    '/me/profile': {
        get: operations['getMeProfile'];
        post: operations['postMeProfile'];
    };
    '/questions/today': {
        get: operations['getQuestionsToday'];
    };
    '/questions/{id}/answers': {
        post: operations['postQuestionsByIdAnswers'];
    };
    '/questions/{id}/answers/{answerId}': {
        delete: operations['deleteQuestionsByIdAnswersByAnswerId'];
        patch: operations['patchQuestionsByIdAnswersByAnswerId'];
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {};
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
    getVersion: {
        responses: {
            200: {
                content: never;
            };
        };
    };
    postAuthKakao: {
        requestBody: {
            content: {
                'application/json': {
                    destination: string;
                };
                'multipart/form-data': {
                    destination: string;
                };
                'text/plain': {
                    destination: string;
                };
            };
        };
        responses: {
            201: {
                content: {
                    'application/json': {
                        url: string;
                    };
                    'multipart/form-data': {
                        url: string;
                    };
                    'text/plain': {
                        url: string;
                    };
                };
            };
            400: {
                content: {
                    'application/json':
                        | {
                              /** @constant */
                              _tag: 'DataParseError';
                          }
                        | {
                              /** @constant */
                              _tag: 'InputRangeError';
                          };
                    'multipart/form-data':
                        | {
                              /** @constant */
                              _tag: 'DataParseError';
                          }
                        | {
                              /** @constant */
                              _tag: 'InputRangeError';
                          };
                    'text/plain':
                        | {
                              /** @constant */
                              _tag: 'DataParseError';
                          }
                        | {
                              /** @constant */
                              _tag: 'InputRangeError';
                          };
                };
            };
        };
    };
    getMe: {
        parameters: {
            header: {
                authorization: string;
            };
        };
        responses: {
            200: {
                content: {
                    'application/json': {
                        id: number;
                        email: string;
                        profile: null | {
                            nickname: string;
                            dateOfBirthYear: number;
                        };
                    };
                    'multipart/form-data': {
                        id: number;
                        email: string;
                        profile: null | {
                            nickname: string;
                            dateOfBirthYear: number;
                        };
                    };
                    'text/plain': {
                        id: number;
                        email: string;
                        profile: null | {
                            nickname: string;
                            dateOfBirthYear: number;
                        };
                    };
                };
            };
            401: {
                content: {
                    'application/json':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'multipart/form-data':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'text/plain':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                };
            };
            404: {
                content: {
                    'application/json': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'text/plain': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                };
            };
        };
    };
    getRecommendation_nickname: {
        parameters: {
            header: {
                authorization: string;
            };
        };
        responses: {
            200: {
                content: {
                    'application/json': {
                        nickname: string;
                    };
                    'multipart/form-data': {
                        nickname: string;
                    };
                    'text/plain': {
                        nickname: string;
                    };
                };
            };
            401: {
                content: {
                    'application/json':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'multipart/form-data':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'text/plain':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                };
            };
            404: {
                content: {
                    'application/json': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'text/plain': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                };
            };
        };
    };
    getMeProfile: {
        parameters: {
            header: {
                authorization: string;
            };
        };
        responses: {
            200: {
                content: {
                    'application/json': {
                        id: number;
                        nickname: string;
                        dateOfBirthYear: number;
                        jobs: {
                            id: number;
                            name: string;
                        }[];
                    };
                    'multipart/form-data': {
                        id: number;
                        nickname: string;
                        dateOfBirthYear: number;
                        jobs: {
                            id: number;
                            name: string;
                        }[];
                    };
                    'text/plain': {
                        id: number;
                        nickname: string;
                        dateOfBirthYear: number;
                        jobs: {
                            id: number;
                            name: string;
                        }[];
                    };
                };
            };
            401: {
                content: {
                    'application/json':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'multipart/form-data':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'text/plain':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                };
            };
            404: {
                content: {
                    'application/json': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'text/plain': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                };
            };
        };
    };
    postMeProfile: {
        parameters: {
            header: {
                authorization: string;
            };
        };
        requestBody: {
            content: {
                'application/json': {
                    nickname: string;
                    dateOfBirthYear: number;
                    jobs: number[];
                };
                'multipart/form-data': {
                    nickname: string;
                    dateOfBirthYear: number;
                    jobs: number[];
                };
                'text/plain': {
                    nickname: string;
                    dateOfBirthYear: number;
                    jobs: number[];
                };
            };
        };
        responses: {
            201: {
                content: {
                    'application/json': {
                        id: number;
                        nickname: string;
                        dateOfBirthYear: number;
                        jobs: {
                            id: number;
                            job: string;
                        }[];
                    };
                    'multipart/form-data': {
                        id: number;
                        nickname: string;
                        dateOfBirthYear: number;
                        jobs: {
                            id: number;
                            job: string;
                        }[];
                    };
                    'text/plain': {
                        id: number;
                        nickname: string;
                        dateOfBirthYear: number;
                        jobs: {
                            id: number;
                            job: string;
                        }[];
                    };
                };
            };
            401: {
                content: {
                    'application/json':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'multipart/form-data':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'text/plain':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                };
            };
            404: {
                content: {
                    'application/json': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'text/plain': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                };
            };
            500: {
                content: {
                    'application/json': {
                        /** @constant */
                        _tag: 'UnInterntionalError';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        _tag: 'UnInterntionalError';
                    };
                    'text/plain': {
                        /** @constant */
                        _tag: 'UnInterntionalError';
                    };
                };
            };
        };
    };
    getQuestionsToday: {
        parameters: {
            header: {
                authorization: string;
            };
        };
        responses: {
            200: {
                content: {
                    'application/json': {
                        id: number;
                        question: string;
                    };
                    'multipart/form-data': {
                        id: number;
                        question: string;
                    };
                    'text/plain': {
                        id: number;
                        question: string;
                    };
                };
            };
            401: {
                content: {
                    'application/json':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'multipart/form-data':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'text/plain':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                };
            };
            500: {
                content: {
                    'application/json': {
                        /** @constant */
                        _tag: 'UnInterntionalError';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        _tag: 'UnInterntionalError';
                    };
                    'text/plain': {
                        /** @constant */
                        _tag: 'UnInterntionalError';
                    };
                };
            };
        };
    };
    postQuestionsByIdAnswers: {
        parameters: {
            header: {
                authorization: string;
            };
            path: {
                id: string | number;
            };
        };
        requestBody: {
            content: {
                'application/json': {
                    answer: string;
                };
                'multipart/form-data': {
                    answer: string;
                };
                'text/plain': {
                    answer: string;
                };
            };
        };
        responses: {
            201: {
                content: {
                    'application/json': {
                        id: number;
                    };
                    'multipart/form-data': {
                        id: number;
                    };
                    'text/plain': {
                        id: number;
                    };
                };
            };
            400: {
                content: {
                    'application/json': {
                        /** @constant */
                        _tag: 'UserAlreadyAnswerTodayQuestionError';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        _tag: 'UserAlreadyAnswerTodayQuestionError';
                    };
                    'text/plain': {
                        /** @constant */
                        _tag: 'UserAlreadyAnswerTodayQuestionError';
                    };
                };
            };
            401: {
                content: {
                    'application/json':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'multipart/form-data':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'text/plain':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                };
            };
        };
    };
    deleteQuestionsByIdAnswersByAnswerId: {
        parameters: {
            header: {
                authorization: string;
            };
            path: {
                id: string | number;
                answerId: string | number;
            };
        };
        responses: {
            204: {
                content: {
                    'application/json': boolean;
                    'multipart/form-data': boolean;
                    'text/plain': boolean;
                };
            };
            400: {
                content: {
                    'application/json': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'text/plain': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                };
            };
            401: {
                content: {
                    'application/json':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'multipart/form-data':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'text/plain':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                };
            };
        };
    };
    patchQuestionsByIdAnswersByAnswerId: {
        parameters: {
            header: {
                authorization: string;
            };
            path: {
                id: string | number;
                answerId: string | number;
            };
        };
        requestBody: {
            content: {
                'application/json': {
                    answer: string;
                };
                'multipart/form-data': {
                    answer: string;
                };
                'text/plain': {
                    answer: string;
                };
            };
        };
        responses: {
            200: {
                content: {
                    'application/json': {
                        id: number;
                        userId: number;
                        createdAt: string;
                        updatedAt: string;
                        questionDistributionId: number;
                        isPublic: boolean;
                    };
                    'multipart/form-data': {
                        id: number;
                        userId: number;
                        createdAt: string;
                        updatedAt: string;
                        questionDistributionId: number;
                        isPublic: boolean;
                    };
                    'text/plain': {
                        id: number;
                        userId: number;
                        createdAt: string;
                        updatedAt: string;
                        questionDistributionId: number;
                        isPublic: boolean;
                    };
                };
            };
            401: {
                content: {
                    'application/json':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'multipart/form-data':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                    'text/plain':
                        | {
                              /** @constant */
                              _tag: 'JWTMalformedError';
                          }
                        | {
                              /** @constant */
                              _tag: 'JWTExpiredError';
                          };
                };
            };
            404: {
                content: {
                    'application/json': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                    'text/plain': {
                        /** @constant */
                        _tag: 'DataNotFoundError';
                    };
                };
            };
        };
    };
}
